@api = http://localhost:5003
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMyOGVkZDg4LWNmMzktNDliMi1hODkxLTVmMTIxMGI1MmYzNyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJleHAiOjE3NDczMTI4OTksImlzcyI6IkF1dGhTZXJ2aWNlIiwiYXVkIjoiQ2xpZW50In0.Ot293c_sP89Cbu-kBapNeVXoOm5342cMsFfYW8KByU4
@articleId = 0196c863-5f76-7747-a52f-9a0a0f6631ee
@userId = 328edd88-cf39-49b2-a891-5f1210b52f37

GET {{api}}/articles
Accept: application/json

###

GET {{api}}/articles/{{articleId}}
Accept: application/json

###

POST {{api}}/articles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "AAAAAAAAAA",
  "categoryId": "12c64621-41a3-44f8-87f8-c939b8d47c90",
  "content": "BBBBBBBBBBBBBBBBB"
}

###

PUT {{api}}/articles/{{articleId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "CCCCCCCCC",
  "categoryId": "2591557b-5353-4bcb-b95c-df79b331e993",
  "content": "This Article is about Programming."
}

###

DELETE {{api}}/articles/{{articleId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

GET {{api}}/articles/{{articleId}}/comments
Accept: application/json
Content-Type: application/json

###

POST {{api}}/articles/{{articleId}}/comments
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "text": "Это первый комментарий!",
  "parentCommentId": null
}

###

DELETE {{api}}/articles/{{articleId}}/comments/0196c866-8e41-772f-a967-680417dfcd51
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

###

GET {{api}}/article-statuses
Accept: application/json

###

GET {{api}}/article-statuses/d6ee7cad-a2ca-4008-9289-634c596f4df2
Accept: application/json

###

GET {{api}}/categories
Accept: application/json

###

GET {{api}}/categories/12c64621-41a3-44f8-87f8-c939b8d47c90
Accept: application/json

###

GET {{api}}/liked-articles?Filter.userId={{userId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###

POST {{api}}/liked-articles/{{articleId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###

DELETE {{api}}/liked-articles/{{articleId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###

GET {{api}}/saved-articles?Filter.userId={{userId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###

POST {{api}}/saved-articles/{{articleId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###

DELETE {{api}}/saved-articles/{{articleId}}
Accept: application/json
Authorization: Bearer {{jwt}}