@api = http://localhost:5003
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMyOGVkZDg4LWNmMzktNDliMi1hODkxLTVmMTIxMGI1MmYzNyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InVzZXIiLCJleHAiOjE3NDcwNzEyMTksImlzcyI6IkF1dGhTZXJ2aWNlIiwiYXVkIjoiQ2xpZW50In0.SBEVCF1Si4eSlndepSgYjBws2IF8gpGc9Q1oKJwvDWE

GET {{api}}/articles
Accept: application/json

###

GET {{api}}/articles/0196c344-25ff-7e07-b134-f9e779e9b95d
Accept: application/json

###

POST {{api}}/articles
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "AAAAAAAAAA",
  "categoryId": "9701bdae-b5b7-40cd-9c36-48553d082807",
  "content": "BBBBBBBBBBBBBBBBB"
}

###

PUT {{api}}/articles/0196c413-3b08-769b-9eea-efc8cdf7e25a
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "CCCCCCCCC",
  "categoryId": "0661ae86-152a-4bd6-be93-5b8cf94c15f1",
  "content": "This Article is about Art."
}

###

DELETE {{api}}/articles/0196c413-3b08-769b-9eea-efc8cdf7e25a
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{jwt}}